lmdpdg: Log errors but generate as many panel drivers as we can
Sometimes there are crashes that cannot be easily fixed, e.g.
  ValueError: DCS_COMPRESSION_MODE is not supported
As far as I know DCS is not supported on mainline.

In this case, it's still nice if we generate panel drivers for all
other panels at least. So let's log them but continue instead of
failing horribly.